Name="Russian"
Aliases=[]

[Translations]
Yes="–î–∞"
No="–ù–µ—Ç"

Student="–£—á–µ–Ω–∏–∫"
Teacher="–£—á–∏—Ç–µ–ª—å"
Admin="–ê–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ç–æ—Ä"

AdminPanelTitle="<b>%s,</b> –¥–æ–±—Ä–æ –ø–æ–∂–∞–ª–æ–≤–∞—Ç—å –≤ –ø–∞–Ω–µ–ª—å –ê–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ç–æ—Ä–∞."
TeacherPanelTitle="<b>%s,</b> –¥–æ–±—Ä–æ –ø–æ–∂–∞–ª–æ–≤–∞—Ç—å –≤ –ø–∞–Ω–µ–ª—å –£—á–∏—Ç–µ–ª—è."
StudentPanelTitle="<b>%s,</b>, –ø—Ä–∏–≤–µ—Ç! –í–æ—Å–ø–æ–ª—å–∑—É–π—Å—è –∏–Ω—Ç–µ—Ä–∞–∫—Ç–∏–≤–Ω—ã–º–∏ –∫–Ω–æ–ø–∫–∞–º–∏."

QuizCreateBtn="–°–æ–∑–¥–∞—Ç—å —Ç–µ—Å—Ç"
QuizListBtn="–ú–æ–∏ —Ç–µ—Å—Ç—ã"
QuizRemoveBtn="–£–¥–∞–ª–∏—Ç—å —Ç–µ—Å—Ç"
QuizStartBtn="–ù–∞—á–∞—Ç—å –ø—Ä–æ—Ö–æ–∂–¥–µ–Ω–∏–µ"
QuizDetailBtn="–î–µ—Ç–∞–ª—å–Ω–∞—è –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è"
QuizStartMessage="üí≠ <b>%s</b>, —Ö–æ—Ç–∏—Ç–µ –ø—Ä–æ–π—Ç–∏ —Ç–µ—Å—Ç \"<b>%s</b>\"?"
QuizNotFound="üîé –î–∞–Ω–Ω–æ–≥–æ —Ç–µ—Å—Ç–∞ –Ω–µ —Å—É—â–µ—Å—Ç–≤—É–µ—Ç."
QuizDetailResultDataNeededMessage="üë§ –•–æ—Ä–æ—à–æ. –¢–µ–ø–µ—Ä—å –æ—Ç–ø—Ä–∞–≤—å—Ç–µ –§–ò–û —á–µ–ª–æ–≤–µ–∫–∞ –¥–ª—è –ø–æ–ª—É—á–µ–Ω–∏—è –¥–µ—Ç–∞–ª—å–Ω–æ–π —Å–≤–æ–¥–∫–∏. (–§–æ—Ä–º–∞—Ç: –ú–∏–Ω–∞–µ–≤ –î–∞–≤–∏–¥ –ú–∏—Ö–∞–π–ª–æ–≤–∏—á)."
QuizDetailResultNotFound="ü§∑‚Äç‚ôÇÔ∏è –î–∞–Ω–Ω—ã–π —á–µ–ª–æ–≤–µ–∫ –Ω–µ –ø—Ä–æ—Ö–æ–¥–∏–ª —Ç–µ—Å—Ç."
QuizWithoutResults="‚ùå –ù–µ—Ç —Ä–µ–∑—É–ª—å—Ç–∞—Ç–æ–≤ –¥–ª—è –¥–∞–Ω–Ω–æ–≥–æ —Ç–µ—Å—Ç–∞."
QuizCreateNameLengthInvalid="–î–ª–∏–Ω–∞ –∏–º–µ–Ω–∏ —Ç–µ—Å—Ç–∞ –Ω–µ —Å–æ–æ—Ç–≤–µ—Ç—Å—Ç–≤—É–µ—Ç –æ–≥—Ä–∞–Ω–∏—á–µ–Ω–∏—è–º (–æ—Ç 5 –¥–æ 256 —Å–∏–º–≤–æ–ª–æ–≤)."
QuizCreatedMessage="–û—Ç–ª–∏—á–Ω–æ. –¢–µ—Å—Ç —Å–æ–∑–¥–∞–Ω.\n–¢–µ–ø–µ—Ä—å –Ω–∞—á–Ω–µ–º –∑–∞–ø–æ–ª–Ω—è—Ç—å –µ–≥–æ –≤–æ–ø—Ä–æ—Å–∞–º–∏.\n\n–ù–∞—á–Ω–µ–º —Å 1-–≥–æ. –û—Ç–ø—Ä–∞–≤—å—Ç–µ —Å–Ω–∞—á–∞–ª–∞ —Å–∞–º –≤–æ–ø—Ä–æ—Å."
QuizQuestionNameLengthInvalid="–î–ª–∏–Ω–∞ –≤–æ–ø—Ä–æ—Å–∞ –Ω–µ —Å–æ–æ—Ç–≤–µ—Ç—Å—Ç–≤—É–µ—Ç –Ω–æ—Ä–º–µ (–æ—Ç 5 –¥–æ 256 —Å–∏–º–≤–æ–ª–æ–≤)."
QuizQuestionCreatedMessage="–ü—Ä–∏–Ω—è—Ç–æ! –û—Ç–ø—Ä–∞–≤—å—Ç–µ —Ç–µ–ø–µ—Ä—å –æ—Ç–≤–µ—Ç—ã –Ω–∞ –¥–∞–Ω–Ω—ã–π –≤–æ–ø—Ä–æ—Å –≤ —Å–ª–µ–¥—É—é—â–µ–º —Ñ–æ—Ä–º–∞—Ç–µ: –ø—Ä–∞–≤–∏–ª—å–Ω—ã–π_–æ—Ç–≤–µ—Ç;–ª–æ–∂–Ω—ã–π_–æ—Ç–≤–µ—Ç_1;...;–ª–æ–∂–Ω—ã–π_–æ—Ç–≤–µ—Ç_5."
QuizAddNewQuestionBtn="–î–æ–±–∞–≤–∏—Ç—å –≤–æ–ø—Ä–æ—Å"
QuizQuestionRemoveBtn="–£–¥–∞–ª–∏—Ç—å —Ç–µ–∫—É—â–∏–π –≤–æ–ø—Ä–æ—Å"
QuizAddingQuestionsStopBtn="–ó–∞–≤–µ—Ä—à–∏—Ç—å"
QuizQuestionAnswerInvalidLength="–î–ª–∏–Ω–∞ –æ—Ç–≤–µ—Ç–∞ –Ω–µ —Å–æ–æ—Ç–≤–µ—Ç—Å—Ç–≤—É–µ—Ç –Ω–æ—Ä–º–µ (–æ—Ç 2 –¥–æ 100 —Å–∏–º–≤–æ–ª–æ–≤).\n–ù–µ–ø–æ–¥—Ö–æ–¥—è—â–∏–π –æ—Ç–≤–µ—Ç: %s"
QuizQuestionAnswersAdded="–í–æ–ø—Ä–æ—Å –≤–∫–ª—é—á–µ–Ω –≤ —Ç–µ—Å—Ç."
QuizCreateStartMessage="–û—Ç–ø—Ä–∞–≤—å—Ç–µ –Ω–∞–∑–≤–∞–Ω–∏–µ —Ç–µ—Å—Ç–∞."
QuizQuestionAnswersCountInvalid="–ö–æ–ª–∏—á–µ—Å—Ç–≤–æ –≤–æ–∑–º–æ–∂–Ω—ã—Ö –æ—Ç–≤–µ—Ç–æ–≤ –¥–æ–ª–∂–Ω–æ –±—ã—Ç—å –Ω–µ –º–µ–Ω–µ–µ 2-—Ö –∏ –Ω–µ –±–æ–ª–µ–µ 5."
QuizQuestionSetNameMessage="–û—Ç–ø—Ä–∞–≤—å—Ç–µ –Ω–∞–∑–≤–∞–Ω–∏–µ –Ω–æ–≤–æ–≥–æ –≤–æ–ø—Ä–æ—Å–∞."
QuizQuestionDeletedMessage="–í–æ–ø—Ä–æ—Å —É–¥–∞–ª–µ–Ω."
QuizRemovedMessage="–¢–µ—Å—Ç \"%s\" —É–¥–∞–ª–µ–Ω."

QuizDetailResultTitle="–¢–µ—Å—Ç–∏—Ä—É–µ–º—ã–π –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å: <b>%s</b> (–ø–æ–ª–Ω–∞—è —Å–≤–æ–¥–∫–∞ –¥–∞–Ω–Ω—ã—Ö)"
QuizDetailResultQuestionLine="%d. <b>%s</b>"
QuizDetailResultCorrectAnswerLine="%s –û—Ç–≤–µ—Ç: %s;"
QuizDetailResultIncorrectAnswerLine="%s –û—Ç–≤–µ—Ç: %s. –ü—Ä–∞–≤–∏–ª—å–Ω—ã–π –æ—Ç–≤–µ—Ç: %s;"

QuizListTitle="–í–∞—à–∏ —Ç–µ—Å—Ç—ã:"
QuizEmptyListTitle="–£ –≤–∞—Å –Ω–µ—Ç —Ç–µ—Å—Ç–æ–≤."

QuestionTitle="–í–æ–ø—Ä–æ—Å %d/%d:"

QuizInfoTitle="–ò–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è –æ —Ç–µ—Å—Ç–µ \"%s\":"
QuizInfoInvitationLinkLine="–°—Å—ã–ª–∫–∞ –Ω–∞ —Ç–µ—Å—Ç: <code>t.me/schtool_bot?start=%s</code>"
QuizInfoQuestionsCountLine="–ö–æ–ª–∏—á–µ—Å—Ç–≤–æ –≤–æ–ø—Ä–æ—Å–æ–≤: <b>%d</b>"
QuizInfoCompletedUsersLine="–†–µ–∑—É–ª—å—Ç–∞—Ç—ã —Ç–µ—Å—Ç–∏—Ä–æ–≤–∞–Ω–∏—è (%d –ø—Ä–æ—à–ª–æ):"
QuizInfoUserResultLine="[%s] <b>%s %s</b>: %d/%d"

QuizAlreadyCompleted="–¢–µ—Å—Ç \"%s\" –±—ã–ª –ø—Ä–æ–π–¥–µ–Ω –í–∞–º–∏ —Ä–∞–Ω–µ–µ. –ü–æ–≤—Ç–æ—Ä–Ω–æ–µ –ø—Ä–æ—Ö–æ–∂–¥–µ–Ω–∏–µ –Ω–µ–≤–æ–∑–º–æ–∂–Ω–æ."
QuizCompletedMessage="‚ö° –í—ã —É—Å–ø–µ—à–Ω–æ –ø—Ä–æ—à–ª–∏ —Ç–µ—Å—Ç \"%s\".\n\n–í–∞—à —Ä–µ–∑—É–ª—å—Ç–∞—Ç <b>%d</b> –ø—Ä–∞–≤–∏–ª—å–Ω—ã—Ö –æ—Ç–≤–µ—Ç–æ–≤ –∏–∑ <b>%d</b> –≤–æ–∑–º–æ–∂–Ω—ã—Ö."

InvitationKeyRequired="–í—ã –æ—Ç—Å—É—Ç—Å—Ç–≤—É–µ—Ç–µ –≤ –±–∞–∑–µ –¥–∞–Ω–Ω—ã—Ö —à–∫–æ–ª—ã.\n\n–ß—Ç–æ–±—ã –ø–æ–¥–∫–ª—é—á–∏—Ç—å—Å—è –∫ —Å–∏—Å—Ç–µ–º–µ Sch, –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –æ—Ç–ø—Ä–∞–≤–∏—Ç—å invitation-–∫–ª—é—á.\n–ï—Å–ª–∏ —Ç–∞–∫–æ–≤–æ–π —É –í–∞—Å –æ—Ç—Å—É—Ç—Å—Ç–≤—É–µ—Ç, —Ç–æ –æ–±—Ä–∞—Ç–∏—Ç–µ—Å—å –∫ —Ç–µ—Ö–Ω–∏—á–µ—Å–∫–æ–º—É –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ç–æ—Ä—É."
InvitationKeyCreateBtn="–°–æ–∑–¥–∞—Ç—å –ø—Ä–∏–≥–ª. –∫–ª—é—á"
InvitationKeyRemoveBtn="–ê–Ω–Ω—É–ª–∏—Ä–æ–≤–∞—Ç—å"
InvitationKeyCreateTitle='–ù–∞—á–∏–Ω–∞–µ–º —Å–æ–∑–¥–∞–≤–∞—Ç—å –∫–ª—é—á <b>%s</b>...'
InvitationKeyCreateName="–ö–∞–∫ –∑–æ–≤—É—Ç —á–µ–ª–æ–≤–µ–∫–∞, –∫–æ—Ç–æ—Ä–æ–º—É —Å–æ–∑–¥–∞–µ—Ç—Å—è –∫–ª—é—á? –£–∫–∞–∂–∏—Ç–µ –≤ —Ñ–æ—Ä–º–∞—Ç–µ –§–∞–º–∏–ª–∏—è –ò–º—è –û—Ç—á–µ—Å—Ç–≤–æ (–Ω–∞–ø—Ä–∏–º–µ—Ä: –ú–∏–Ω–∞–µ–≤ –î–∞–≤–∏–¥ –ú–∏—Ö–∞–π–ª–æ–≤–∏—á)."
InvitationKeyNameIncorrect="–ù–µ–≤–µ—Ä–Ω–æ —É–∫–∞–∑–∞–Ω–æ –§–ò–û. –£–∫–∞–∂–∏—Ç–µ –ø–æ —Å–ª–µ–¥—É—é—â–µ–π —Ñ–æ—Ä–º–µ: –§–∞–º–∏–ª–∏—è –ò–º—è –û—Ç—á–µ—Å—Ç–≤–æ."
InvitationKeyNameSaved="–û—Ç–ª–∏—á–Ω–æ. –í–ª–∞–¥–µ–ª—å—Ü–∞ –∫–ª—é—á–∞ –∑–æ–≤—É—Ç: <b>%s %s %s</b>. –í—Å–µ –≤–µ—Ä–Ω–æ?"
InvitationKeyNameRefillMessage="–•–æ—Ä–æ—à–æ. –û—Ç–ø—Ä–∞–≤—å—Ç–µ –Ω–æ–≤–æ–µ –§–ò–û."
InvitationKeyStageRoleMessage="–£—Ä–∞! –ö–ª—é—á –ø–æ—á—Ç–∏ –≥–æ—Ç–æ–≤ –∫ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—é... –û—Å—Ç–∞–ª–æ—Å—å –ª–∏—à—å –≤—ã–±—Ä–∞—Ç—å —Ä–æ–ª—å –≤–ª–∞–¥–µ–ª—å—Ü—É. –ü–æ —É–º–æ–ª—á–∞–Ω–∏—é —Å—Ç–æ–∏—Ç —Ä–æ–ª—å —É—á–µ–Ω–∏–∫–∞."
InvitationKeyCreated="–ö–ª—é—á —Å–æ–∑–¥–∞–Ω.\n\n–í–ª–∞–¥–µ–ª–µ—Ü: %s\n–†–æ–ª—å: %s\n–ò—Å—Ç–µ–∫–∞–µ—Ç: %s"
InvitationKeyRemoved="–ö–ª—é—á <b>%s</b> –∞–Ω–Ω—É–ª–∏—Ä–æ–≤–∞–Ω."
InvitationKeyApplied="<b>%s</b>, –í—ã —É—Å–ø–µ—à–Ω–æ –∑–∞—Ä–µ–≥–∏—Å—Ç—Ä–∏—Ä–æ–≤–∞–Ω—ã –≤ –¥–æ–ª–∂–Ω–æ—Å—Ç–∏ %s."
InvitationKeyInvalid="–î–∞–Ω–Ω—ã–π –ø—Ä–∏–≥–ª–∞—Å–∏—Ç–µ–ª—å–Ω—ã–π –∫–ª—é—á –Ω–µ –¥–µ–π—Å—Ç–≤–∏—Ç–µ–ª–µ–Ω."
RuntimeError="–í–æ–∑–Ω–∏–∫–ª–∞ –Ω–µ–ø—Ä–µ–¥–≤–∏–¥–µ–Ω–Ω–∞—è –æ—à–∏–±–∫–∞. –ü–æ–≤—Ç–æ—Ä–∏—Ç–µ —Å–≤–æ–π –∑–∞–ø—Ä–æ—Å —á—É—Ç—å –ø–æ–∑–∂–µ. (err: %s)"